### ISSUE TITLE
#adminconsole vCenterConfig shows only production site details...

### ISSUE THREAD

**Issue by cunla** [cunla/RPSP#20]

**Comment by cunla** [comment]
Bug in VirtualConfigurationServiceImpl line 43:
VirtualCenterConfiguration clusterVc = clusterVcs.stream().collect(Collectors.toList()).get(0);

In case of multiple VCs, should show all and not just the first.

Try system 10.63.231.18, cluster 3025632502083912711

**Comment by shpboris** [comment]
This is the scenario that we decided not to support - more than one VC per cluster.
